language: generic
services:
- docker
before_install:
- make install
script:
- composer create-project
    wp-coding-standards/wpcs
    --no-dev
- wpcs/vendor/bin/phpcs
    --config-set installed_paths wpcs/
- wpcs/vendor/squizlabs/php_codesniffer/bin/phpcs
    --ignore=flush-opcache/admin/opcache.php,flush-opcache/admin/js/d3.min.js
    --standard=WordPress
    flush-opcache/
deploy:
  provider: script
  script: bash travis-to-svn.sh
  on:
    tags: true
    branch: master
    repo: nierdz/flush-opcache
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/flush-opcache
  - SVN_USERNAME=mnttech
