language: generic
services:
- docker
before_install:
- make install
script:
- make tests
deploy:
  provider: script
  script: bash travis-to-svn.sh
  on:
    tags: true
    branch: master
    repo: nierdz/flush-opcache
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/flush-opcache
  - SVN_USERNAME=mnttech
